Simple Web Server for JavaScript
utk-cs340-fall24/notJSON pull request #39
Opened 2024-10-02 20:51 UTC by jasontwest

2024-10-02 22:58 UTC, landon-boone2001 approved these changes

2024-10-03 00:30 UTC, jacksonmowry commented
We don't want to commit node_modules to our git repo. Look into using the `.gitignore` to exclude that entire directory from being commited.

2024-10-03 00:31 UTC, jacksonmowry requested changes
Remove `node_modules` from this commit

2024-10-03 12:02 UTC, jacksonmowry approved these changes
Good

2024-10-03 12:02 UTC, merged